- name: Configure Server
  hosts: all
  remote_user: "{{ ansible_settings.ansible_user }}"
  vars_files:
    - config/ansible_vars.yaml
  tasks:
    - name: Copy scripts
      ansible.builtin.copy:
        src: 'scripts/'
        dest: '/opt/scripts'
        mode: '0770'
        owner: 'root'
        group: 'root'
      become: true

    - name: Install docker
      ansible.builtin.include_tasks: tasks/install-docker.yaml
      when: task_switches.install_docker

    - name: Install packages
      ansible.builtin.include_tasks: tasks/install-packages.yaml
      when: task_switches.install_packages

    - name: Configure storage
      ansible.builtin.include_tasks: tasks/configure-storage.yaml
      when: task_switches.configure_storage

    - name: Configure IAM
      ansible.builtin.include_tasks: tasks/configure-iam.yaml
      when: task_switches.configure_iam

    - name: Configure Shares
      ansible.builtin.include_tasks: tasks/configure-shares.yaml
      when: task_switches.configure_shares

    - name: Set power schedule
      ansible.builtin.include_tasks: tasks/set-power-schedule.yaml
      when: task_switches.set_power_schedule

    - name: Deploy containers
      ansible.builtin.include_tasks: tasks/deploy-containers.yaml
      when: task_switches.deploy_containers

    - name: Install services
      ansible.builtin.include_tasks: tasks/install-services.yaml
      when: task_switches.install_services

    - name: Configure maintenance
      ansible.builtin.include_tasks: tasks/configure-maintenance.yaml
      when: task_switches.configure_maintenance
