- name: Update repositories
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - samba
  become: true

- name: Create user groups for folders and shares
  ansible.builtin.group:
    name: '{{ item.name }}'
    state: present
  become: true
  loop: '{{ folders + shares }}'

- name: Create folders and shares
  ansible.builtin.file:
    path: '/mnt/storage/{{ item.name }}'
    state: directory
    mode: '{{ item.mode }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.owner | default(item.name) }}'
  loop: '{{ folders + shares }}'
  become: true

- name: Create samba shares
  ansible.builtin.template:
    src: 'config/templates/smb.conf.j2'
    dest: '/etc/samba/smb.conf'
    mode: '0640'
  become: true

- name: Restart Samba
  ansible.builtin.service:
    name: smbd
    state: restarted
  become: true
