- name: Create snapraid runner configuration
  ansible.builtin.template:
    src: 'config/templates/snapraid-runner.conf.j2'
    dest: '/opt/snapraid-runner/snapraid-runner.conf'
    mode: '0640'
  become: true

- name: Create scripts directory
  ansible.builtin.file:
    path: '/opt/scripts'
    state: directory
    mode: '0640'
    owner: 'root'
    group: 'root'
  become: true

- name: Create maintenance script
  ansible.builtin.template:
    src: 'config/templates/maintenance.sh.j2'
    dest: '/opt/scripts/maintenance.sh'
    mode: '0750'
    owner: 'root'
    group: 'root'
  become: true

- name: Create maintenance job
  ansible.builtin.cron:
    name: system-maintenance
    user: 'root'
    hour: '{{ (maintenance.start_time == "before_shutdown") | ternary(power.shutdown_time.split(":")[0] | int, maintenance.start_time.split(":")[0] | int) }}'
    minute: '{{ (maintenance.start_time == "before_shutdown") | ternary(power.shutdown_time.split(":")[1] | int, maintenance.start_time.split(":")[1] | default(0) | int) }}' # noqa: yaml[line-length]
    env: true
    job: '/opt/scripts/maintenance.sh > /opt/scripts/maintenance.log 2>&1 | ts'
  become: true

- name: Set AWS access key id environment variable
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^AWS_ACCESS_KEY_ID='
    line: 'AWS_ACCESS_KEY_ID={{ software.backup.aws_access_key_id }}'
  become: true

- name: Set AWS secret access key environment variable
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^AWS_SECRET_ACCESS_KEY='
    line: 'AWS_SECRET_ACCESS_KEY={{ software.backup.aws_secret_access_key }}'
  become: true
