- name: Create snapraid runner configuration
  ansible.builtin.template:
    src: 'config/templates/snapraid-runner.conf.j2'
    dest: '/opt/snapraid-runner/snapraid-runner.conf'
    mode: '0640'
  become: true

- name: Create rclone directory
  ansible.builtin.file:
    path: '/opt/rclone'
    state: directory
    mode: '0640'
    owner: 'root'
    group: 'root'
  become: true

- name: Create rclone configuration
  ansible.builtin.template:
    src: 'config/templates/rclone.conf.j2'
    dest: '/opt/rclone/rclone.conf'
    mode: '0640'
  become: true

- name: Create scripts directory
  ansible.builtin.file:
    path: '/opt/scripts'
    state: directory
    mode: '0640'
    owner: 'root'
    group: 'root'
  become: true

- name: Create maintenance script
  ansible.builtin.template:
    src: 'config/templates/maintenance.sh.j2'
    dest: '/opt/scripts/maintenance.sh'
    mode: '0640'
  become: true

- name: Create maintenance job
  ansible.builtin.cron:
    name: system-maintenance
    user: '{{ ansible_settings.ansible_user }}'
    hour: '{{ (maintenance.start_time == "before_shutdown") | ternary(power.shutdown_time.split(":")[0] | int, maintenance.start_time.split(":")[0] | int) }}'
    minute: '{{ (maintenance.start_time == "before_shutdown") | ternary(power.shutdown_time.split(":")[1] | int, maintenance.start_time.split(":")[1] | default(0) | int) }}' # noqa: yaml[line-length]
    job: '/opt/scripts/maintenance.sh'
  become: true
