- name: Calculate sleep seconds
  ansible.builtin.script:
    cmd: 'scripts/power_schedule.py "{{ power.startup_time }}" "{{ power.shutdown_time }}"'
  delegate_to: '127.0.0.1'
  register: sleep_seconds_output
  when: (power.schedule_enabled and maintenance.start_time != 'before_shutdown')

- name: Set sleep seconds fact
  ansible.builtin.set_fact:
    sleep_seconds: '{{ sleep_seconds_output.stdout }}'
  when: (power.schedule_enabled and maintenance.start_time != 'before_shutdown')

- name: Add to PATH
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/usr/sbin'
    state: present
  become: true

- name: Set power schedule
  ansible.builtin.cron:
    name: rtcwake
    user: '{{ ansible_settings.ansible_user }}'
    hour: '{{ power.shutdown_time.split(":")[0] | int }}'
    minute: '{{ power.shutdown_time.split(":")[1] | int }}'
    # The user that this cron job is assigned to needs passwordless sudo for /usr/sbin/rtcwake
    # The job also needs to run with sudo because rtcwake relies on the motherboard's real time clock (RTC)
    # The default is /dev/rtc0 and /dev components are enumerated at each boot so permission changes won't persist beyond a reboot
    job: 'sudo rtcwake --mode off --seconds {{ sleep_seconds | default(0) }}'
    state: '{{ "present" if (power.schedule_enabled and maintenance.start_time != "before_shutdown") else "absent" }}' # TODO: Test to make sure this is working
  become: true
